version: '3.9'

services:

  db:
    build: .
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 12345
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  db:
